
name: Get English model files

on:
  workflow_dispatch:
     inputs:
      source_branch:
        description: 'The core repository branch to pull translation YAML files from (e.g. develop)'
        required: true
      source_folder:
        description: 'The folder in the core branch to pull translation YAML files from (e.g. model)'
        required: true
      new_branch_name:
        description: 'The name of the new branch to create in this repository with the pulled files (e.g. trans_2.0.8)'
        required: true

jobs:
  shared-workflow:
    uses: owaspsamm/core/.github/workflows/reusable-create-translation-branch.yml@438ef84c34d08befb5cd413a3344d1e6e1f75e9e
    with:
      source_branch: ${{inputs.source_branch}}
      source_folder: ${{inputs.source_folder}}
      new_branch_name: ${{inputs.new_branch_name}}